name: Laravel

on:
  push:
<<<<<<< HEAD
    branches: [ main ]
  pull_request:
    branches: [ main ]
=======
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
>>>>>>> 1b8fcd5fedf783df346660b0bbcf2aa16822bbce

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2 
    
<<<<<<< HEAD
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.test', '.env');"
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |        
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
       
       # This job is to cache the node modules in order to reduce the time it would take to run
    - name: Use cached node_modules
      uses: actions/setup-node@v2
      with:
         directory: zc_plugin_expenses
         
         #this job installs intalls yarn dependencies on the github runner
         #and also to build the static files that would be transferred to server later
    - name: Install dependencies
      run: |
        npm install
        npm run production
=======
>>>>>>> 1b8fcd5fedf783df346660b0bbcf2aa16822bbce
      
    - name: Git Pull on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ZURI_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
       # key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/expenses.zuri.chat
<<<<<<< HEAD
          sudo rm composer.lock
          sudo rm package-lock.json
          git pull origin dev
          git branch -r
          git stash
          composer install
          npm install
          
        # this job copies the build folder from GitHub runners to the server with sftp, make sure the paths are correct      
    - name: copy build to server
      uses: Creepios/sftp-action@v1.0.1
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.ZURI_HOST }}
        password: ${{ secrets.PASSWORD }}
        localPath: './zc_plugin_expenses/webpack.mix.js'
        remotePath: '/var/www/expenses.zuri.chat'
=======
          git stash
          git pull origin
          git branch -r          
          composer install
          yarn
>>>>>>> 1b8fcd5fedf783df346660b0bbcf2aa16822bbce
